### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [PhoenixChen2016/TDD_Homework2#1]
請見在各個 commit 的 comments。
1. production  code 偷跑的問題，是工程師的人性，可以慢慢調整養成習慣。
2. 時時檢視是否需要重構，越即時重構，代表重構的範圍越小，effort 越低，且後續 TDD 再新增 production  code 時更清楚輕鬆。
3. C#的一些資料結構的選擇，以及 API 設計的易用性，還有改善空間。

**Comment by phoenix-chen-2016** [comment]
再調整了程式
